version: '3.8'

services:
  wdlp:
    build:
      context: .
    container_name: wdlp_container
    volumes:
      - ./data:/data  # Mount the local data directory
    environment:
      - PYTHONUNBUFFERED=1  # Enable real-time logging
    command: >
      --input /data/l_amat.zip
      --output /data/output
      --format jsonl
      --verbose
