services:
  wdlp:
    build:
      context: .
    container_name: wdlp_container
    volumes:
      - ./data:/data  # Mount the local data directory
    environment:
      - PYTHONUNBUFFERED=1  # Enable real-time logging
    command: --input /data/l_amat.zip --output /data/output

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: wdlp_test_container
    volumes:
      - ./data:/data  # Mount the local data directory
      - ./tests:/app/tests  # Mount tests directory for live updates
      - ./src:/app/src  # Mount source directory for live updates
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker tests
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: --cov=wdlp --cov-report=term-missing tests/  # Run all tests including Docker tests
