from pydantic import BaseModel, Field
from typing import Optional

class AMRecord(BaseModel):
    Record_Type: Optional[str] = Field(None, min_length=2, max_length=2, description="Record type identifier for AM records")
    Unique_System_Identifier: Optional[int] = Field(None, ge=0, le=999999999, description="Unique system identifier")
    ULS_File_Number: Optional[str] = Field(None, min_length=1, max_length=14, description="ULS file number")
    EBF_Number: Optional[str] = Field(None, max_length=30, description="EBF number")
    Call_Sign: Optional[str] = Field(None, max_length=10, description="Call sign")
    Operator_Class: Optional[str] = Field(None, min_length=1, max_length=1, description="Operator class")
    Group_Code: Optional[str] = Field(None, min_length=1, max_length=1, description="Group code")
    Region_Code: Optional[int] = Field(None, ge=0, le=255, description="Region code")
    Trustee_Call_Sign: Optional[str] = Field(None, max_length=10, description="Trustee call sign")
    Trustee_Indicator: Optional[str] = Field(None, min_length=1, max_length=1, description="Trustee indicator")
    Physician_Certification: Optional[str] = Field(None, min_length=1, max_length=1, description="Physician certification")
    VE_Signature: Optional[str] = Field(None, min_length=1, max_length=1, description="VE signature")
    Systematic_Call_Sign_Change: Optional[str] = Field(None, min_length=1, max_length=1, description="Systematic call sign change")
    Vanity_Call_Sign_Change: Optional[str] = Field(None, min_length=1, max_length=1, description="Vanity call sign change")
    Vanity_Relationship: Optional[str] = Field(None, max_length=12, description="Vanity relationship")
    Previous_Call_Sign: Optional[str] = Field(None, max_length=10, description="Previous call sign")
    Previous_Operator_Class: Optional[str] = Field(None, min_length=1, max_length=1, description="Previous operator class")
    Trustee_Name: Optional[str] = Field(None, max_length=50, description="Trustee name")

class ENRecord(BaseModel):
    Record_Type: Optional[str] = Field(None, min_length=2, max_length=2, description="Record type identifier for EN records")
    Unique_System_Identifier: Optional[int] = Field(None, ge=0, le=999999999, description="Unique system identifier")
    ULS_File_Number: Optional[str] = Field(None, min_length=1, max_length=14, description="ULS file number")
    EBF_Number: Optional[str] = Field(None, max_length=30, description="EBF number")
    Call_Sign: Optional[str] = Field(None, max_length=10, description="Call sign")
    Entity_Type: Optional[str] = Field(None, min_length=2, max_length=2, description="Entity type")
    Licensee_ID: Optional[str] = Field(None, max_length=9, description="Licensee ID")
    Entity_Name: Optional[str] = Field(None, max_length=200, description="Entity name")
    First_Name: Optional[str] = Field(None, max_length=20, description="First name")
    MI: Optional[str] = Field(None, min_length=1, max_length=1, description="Middle initial")
    Last_Name: Optional[str] = Field(None, max_length=20, description="Last name")
    Suffix: Optional[str] = Field(None, max_length=3, description="Suffix")
    Phone: Optional[str] = Field(None, min_length=10, max_length=10, description="Phone number")
    Fax: Optional[str] = Field(None, min_length=10, max_length=10, description="Fax number")
    Email: Optional[str] = Field(None, max_length=50, description="Email address")
    Street_Address: Optional[str] = Field(None, max_length=60, description="Street address")
    City: Optional[str] = Field(None, max_length=20, description="City")
    State: Optional[str] = Field(None, min_length=2, max_length=2, description="State")
    Zip_Code: Optional[str] = Field(None, max_length=9, description="Zip code")
    PO_Box: Optional[str] = Field(None, max_length=20, description="PO Box")
    Attention_Line: Optional[str] = Field(None, max_length=35, description="Attention line")
    SGIN: Optional[str] = Field(None, max_length=3, description="SGIN")
    FCC_Registration_Number: Optional[str] = Field(None, max_length=10, description="FCC registration number")
    Applicant_Type_Code: Optional[str] = Field(None, min_length=1, max_length=1, description="Applicant type code")
    Applicant_Type_Code_Other: Optional[str] = Field(None, max_length=40, description="Other applicant type code")
    Status_Code: Optional[str] = Field(None, min_length=1, max_length=1, description="Status code")
    Status_Date: Optional[str] = Field(None, description="Status date (mm/dd/yyyy)")
    GHz_License_Type: Optional[str] = Field(None, min_length=1, max_length=1, description="3.7 GHz license type")
    Linked_Unique_System_Identifier: Optional[int] = Field(None, ge=0, le=999999999, description="Linked unique system identifier")
    Linked_Call_Sign: Optional[str] = Field(None, max_length=10, description="Linked call sign")
